controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    joints:
      - RTz
      - RTx
      - RTy
      - RSy
      - RFy
      - RFx
      - LTz
      - LTx
      - LTy
      - LSy
      - LFy
      - LFx
      - RAy
      - RAx
      - RFAy
      - LAy
      - LAx
      - LFAy
      - Hz
      - Hy

joint_trajectory_controller:
  ros__parameters:
    joints:
      - RTz
      - RTx
      - RTy
      - RSy
      - RFy
      - RFx
      - LTz
      - LTx
      - LTy
      - LSy
      - LFy
      - LFx
      - RAy
      - RAx
      - RFAy
      - LAy
      - LAx
      - LFAy
      - Hz
      - Hy

    command_interfaces:
      - position
      - velocity
    
    state_interfaces:
      - position
      - velocity
    action_monitor_rate: 200.0

    allow_partial_joints_goal: false
    open_loop_control: true

velocity_controller:
  ros__parameters:
    joints:
      - RTz
      - RTx
      - RTy
      - RSy
      - RFy
      - RFx
      - LTz
      - LTx
      - LTy
      - LSy
      - LFy
      - LFx
      - RAy
      - RAx
      - RFAy
      - LAy
      - LAx
      - LFAy
      - Hz
      - Hy

    command_interfaces:
      - position
      - velocity
    
    state_interfaces:
      - position
      - velocity

