controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - RTz
      - RTx
      - RTy
      - RSy
      - RFy
      - RFx
      - LTz
      - LTx
      - LTy
      - LSy
      - LFy
      - LFx
      - RAy
      - RAx
      - RFAy
      - LAy
      - LAx
      - LFAy
      - Hz
      - Hy
    command_joints:
      - RTz
      - RTx
      - RTy
      - RSy
      - RFy
      - RFx
      - LTz
      - LTx
      - LTy
      - LSy
      - LFy
      - LFx
      - RAy
      - RAx
      - RFAy
      - LAy
      - LAx
      - LFAy
      - Hz
      - Hy

    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_nonzero_velocity_at_trajectory_end: false

    